import React, { useState, useEffect } from "react";
import { Card, FormField, Loader } from "../components";
// import {count} from './CreatePost';
const Home = () => {
  const [loading, setloading] = useState(false);
  const [allposts, setposts] = useState(null);
  const [searchText, setsearchText] = useState("");
  const [storeinfo, setstoreinfo] = useState(null);
  const [check, setcheck] = useState(false);
  // key={post.id}
  const RenderCards = ({ data}) => {
    if (data?.length > 0) {
      
        data.map((p) => {
          const d={...p};
          setstoreinfo(d);
        }
      

        // <Card key={post[0]._id} {...post[0]} />
        )
      }
    // return (
    //   <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">
    //     {title}
    //   </h2>
    // );
  };
  // RenderCards({allposts});

  const RenderCards_2 = ({ data, title }) => {
    
    // if (data?.length > 0) 
    // {
    //   data.map((p) => {
    //     const d={...p};
    //     setstoreinfo(d);
    //   })
    //   // console.log(storeinfo.length);
    //   for(let i=0;i<1;i++){
    //     return <Card _id={storeinfo[i]._id} name={storeinfo[i].name} prompt={storeinfo[i].prompt} photo={storeinfo[i].photo}  />
    //   }
    //   }
    // return (
    //   <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">
    //     {title}
    //   </h2>
    // );
    if (data?.length > 0) {
      return (
        data.map((post) => 
        <Card key={post[0]._id} {...post[0]} />)
      );
    }
  
    return (
      <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
    );
  };



  const fetchPost=async()=>{
    setloading(true);
    try {
      const response = await fetch("http://localhost:4444/api/v1/post", {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          // 'Content-Type': 'application/x-www-form-urlencoded',
        },
      });
     
      const result=await response.json();
      
      setposts(result.data.reverse());
      // console.log(result.data);
    } catch (error) {
      console.log(error);
    } finally {
      setloading(false);
      setcheck(true);
    
    }
  }

  useEffect(()=>{
    fetchPost();
  },[]);
  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[32px]">The Community Showcase</h1>
        <p className="mt-2 text-[#666e75] text-[16px] max-w[500px]">
          Browse through a collection of imaginative and visually stunning
          imagesgenerated by DALL-E AI
        </p>
      </div>
      <div className="mt-16">
        <FormField />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center ">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing Resuls for{" "}
                <span className="text-[#222328]">{searchText}</span>:
              </h2>
            )}
           {check && (
             <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText  ? (
                <RenderCards_2
                  data={[]}
                  title="No Search Results Found"
                />
              ) : (
                <RenderCards_2 data={[allposts]} title="No Posts Yet" />
              )}
            </div>
           )}
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
